### ISSUE TITLE
好像没找到父目录Could not find 'pyproject.toml' in any parent directory

### ISSUE THREAD

**Issue by Graduallyhui** [hanasa2023/nonebot-plugin-updater#11]
![AGII4_}U7 3$Y ~M)VXT@`2](https://github.com/user-attachments/assets/a6844a5e-def8-4136-937f-7a9b9b9ebc63)
![EHS2{$WH)DG0Q4}MD{4%AED](https://github.com/user-attachments/assets/79162464-1c43-4517-aa88-6e228c8a04a3)

**Comment by Graduallyhui** [comment]
![AGII4_}U7 3$Y ~M)VXT@`2](https://github.com/user-attachments/assets/db1fb2c2-3dce-4bca-94b3-b2014e9f6f7f)

**Comment by Graduallyhui** [comment]
> 能否将您的bot根目录也截图发一下？

大佬你好，我的bot根目录就是/app/mybot/

**Comment by hanasa2023** [comment]
> > 能否将您的bot根目录也截图发一下？
> 
> 
> 
> 大佬你好，我的bot根目录就是/app/mybot/

我要看的是根目录下的文件🧐，你是不是用的bot.py

**Comment by hanasa2023** [comment]
不好意思之前没看清，现已在0.2.0修复。

**Comment by Graduallyhui** [comment]
> 不好意思之前没看清，现已在0.2.0修复。

可以了谢谢大佬
