### ISSUE TITLE
[Bug]无法重启

### ISSUE THREAD

**Issue by Florenz0707** [hanasa2023/nonebot-plugin-updater#13]
想知道重启一次大概要花多少时间呢？五分钟了还未响应......
日志如图：
<img width="1025" alt="屏幕截图 2024-11-20 122432" src="https://github.com/user-attachments/assets/7c7b4b5a-8f6b-45b5-a7eb-2ab4b2181078">

**Comment by hanasa2023** [comment]
能否提一下您所使用的插件版号以及python版本。如果您使用的是0.1.2以下的版本，确实会出现关闭后无法重启的情况

**Comment by Florenz0707** [comment]
updater: 0.2.0, htmlrender: 0.3.5, apscheduler: 0.5.0。而且貌似今天还出现了安装插件时，无论是能找到插件，进行安装还是timeout，终端都会无响应的情况。
<img width="1213" alt="屏幕截图 2024-11-20 235703" src="https://github.com/user-attachments/assets/2cc3e92d-e360-4dfd-843f-3ee0ca99dafd">
ge个人怀疑与等待browser或者其他应用形成的死锁有关。
ps.在出现以上情况后，使用ctrl-c进行强制关闭，nonebot也无法正常结束运行。

**Comment by hanasa2023** [comment]
看样子是因为有什么task阻塞了uvicorn的关闭，从而阻塞了整个流程的进行。在0.2.1中加入了关闭超时检测，当uvicron超时时会强制关闭uvicron。~~虽然这看上去并不是什么安全的办法，但行之有效~~。您可以查看0.2.1是否已修复当前问题。

**Comment by Florenz0707** [comment]
感谢您的改进。虽然现在我的项目已无法兼容该插件了，但还是为您做出的努力表示感谢。

**Comment by hanasa2023** [comment]
很遗憾在此插件最后没有帮到您，🤝
