### ISSUE TITLE
插件报错

### ISSUE THREAD

**Issue by wzq10314** [hanasa2023/nonebot-plugin-updater#2]
10-10 18:37:08 [ERROR] nonebot | Running AlconnaMatcher(type='', module=nonebot_plugin_updater.commands, lineno=39) failed.
Traceback (most recent call last):
  File "<string>", line 15, in <module>
  File "/root/nonebot11/.venv/lib/python3.10/site-packages/nonebot/__init__.py", line 335, in run
    get_driver().run(*args, **kwargs)
  File "/root/nonebot11/.venv/lib/python3.10/site-packages/nonebot/drivers/fastapi.py", line 186, in run
    uvicorn.run(
  File "/root/nonebot11/.venv/lib/python3.10/site-packages/uvicorn/main.py", line 579, in run
    server.run()
  File "/root/nonebot11/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/root/nonebot11/.venv/lib/python3.10/site-packages/nonebot/message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "/root/nonebot11/.venv/lib/python3.10/site-packages/nonebot/message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/root/nonebot11/.venv/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 850, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/root/nonebot11/.venv/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 825, in simple_run
    await handler(
  File "/root/nonebot11/.venv/lib/python3.10/site-packages/nonebot/dependencies/__init__.py", line 94, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/root/nonebot11/.venv/lib/python3.10/site-packages/nonebot_plugin_updater/commands.py", line 80, in _
    plugin_update_list: list[PluginInfo] = await get_plugin_update_list()
  File "/root/nonebot11/.venv/lib/python3.10/site-packages/nonebot_plugin_updater/utils/common.py", line 45, in get_plugin_update_list
    lastest_version = await get_plugin_latest_version(plugin)
  File "/root/nonebot11/.venv/lib/python3.10/site-packages/nonebot_plugin_updater/utils/common.py", line 18, in get_plugin_latest_version
    data: PypiResponse = PypiResponse(**response.json())
  File "/root/nonebot11/.venv/lib/python3.10/site-packages/pydantic/main.py", line 212, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for PypiResponse
info.author_email
  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.9/v/string_type

**Comment by hanasa2023** [comment]
我这边无法复现上述情况，能否提供更详细的信息
- 是在插件启动时报错还是执行某一命令时报错？
- 能否提供.env文件的配置
- 插件的版本号

**Comment by wzq10314** [comment]
> 我这边无法复现上述情况，能否提供更详细的信息
> 
> * 是在插件启动时报错还是执行某一命令时报错？
> * 能否提供.env文件的配置

> * 插件的版本号
运行没有报错，执行除/获取插件列表 这个命令以外全都会报错。

![9f5418c6-66c3-4750-aeb4-79d81db4ca29](https://github.com/user-attachments/assets/4ff5e215-d394-495f-9af4-11b6881b20cb)
![0c4435e3-5eab-4127-a931-94af0f29824d](https://github.com/user-attachments/assets/47177c66-4224-40dc-96ff-384a8e7e89f4)

**Comment by wzq10314** [comment]
66610821 from 245176264@[群:163722659] '/检查插件更新'
10-10 23:59:27 [INFO] nonebot | Event will be handled by AlconnaMatcher(type='', module=nonebot_plugin_updater.commands, lineno=39)
10-10 23:59:27 [INFO] nonebot | AlconnaMatcher(type='', module=nonebot_plugin_updater.commands, lineno=39) running complete
10-10 23:59:27 [ERROR] nonebot | Running AlconnaMatcher(type='', module=nonebot_plugin_updater.commands, lineno=39) failed.
Traceback (most recent call last):
  File "<string>", line 15, in <module>
  File "/root/nonebot11/.venv/lib/python3.10/site-packages/nonebot/__init__.py", line 335, in run
    get_driver().run(*args, **kwargs)
  File "/root/nonebot11/.venv/lib/python3.10/site-packages/nonebot/drivers/fastapi.py", line 186, in run
    uvicorn.run(
  File "/root/nonebot11/.venv/lib/python3.10/site-packages/uvicorn/main.py", line 579, in run
    server.run()
  File "/root/nonebot11/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/root/nonebot11/.venv/lib/python3.10/site-packages/nonebot/message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "/root/nonebot11/.venv/lib/python3.10/site-packages/nonebot/message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/root/nonebot11/.venv/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 850, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/root/nonebot11/.venv/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 825, in simple_run
    await handler(
  File "/root/nonebot11/.venv/lib/python3.10/site-packages/nonebot/dependencies/__init__.py", line 94, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/root/nonebot11/.venv/lib/python3.10/site-packages/nonebot_plugin_updater/commands.py", line 80, in _
    plugin_update_list: list[PluginInfo] = await get_plugin_update_list()
  File "/root/nonebot11/.venv/lib/python3.10/site-packages/nonebot_plugin_updater/utils/common.py", line 45, in get_plugin_update_list
    lastest_version = await get_plugin_latest_version(plugin)
  File "/root/nonebot11/.venv/lib/python3.10/site-packages/nonebot_plugin_updater/utils/common.py", line 18, in get_plugin_latest_version
    data: PypiResponse = PypiResponse(**response.json())
  File "/root/nonebot11/.venv/lib/python3.10/site-packages/pydantic/main.py", line 212, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for PypiResponse
info.author_email
  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.9/v/string_type
--------------------------------------------------------------------------------------------------------------------------------------------
35731268 from 245176264@[群:163722659] '/更新插件 name nonebot-plugin-updater'
10-11 00:00:13 [INFO] nonebot | Event will be handled by AlconnaMatcher(type='', module=nonebot_plugin_updater.commands, lineno=42)
10-11 00:00:13 [INFO] nonebot | AlconnaMatcher(type='', module=nonebot_plugin_updater.commands, lineno=42) running complete
10-11 00:00:13 [ERROR] nonebot | Running AlconnaMatcher(type='', module=nonebot_plugin_updater.commands, lineno=42) failed.
Traceback (most recent call last):
  File "<string>", line 15, in <module>
  File "/root/nonebot11/.venv/lib/python3.10/site-packages/nonebot/__init__.py", line 335, in run
    get_driver().run(*args, **kwargs)
  File "/root/nonebot11/.venv/lib/python3.10/site-packages/nonebot/drivers/fastapi.py", line 186, in run
    uvicorn.run(
  File "/root/nonebot11/.venv/lib/python3.10/site-packages/uvicorn/main.py", line 579, in run
    server.run()
  File "/root/nonebot11/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/root/nonebot11/.venv/lib/python3.10/site-packages/nonebot/message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "/root/nonebot11/.venv/lib/python3.10/site-packages/nonebot/message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/root/nonebot11/.venv/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 850, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/root/nonebot11/.venv/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 825, in simple_run
    await handler(
  File "/root/nonebot11/.venv/lib/python3.10/site-packages/nonebot/dependencies/__init__.py", line 94, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/root/nonebot11/.venv/lib/python3.10/site-packages/nonebot_plugin_updater/commands.py", line 108, in _
    plugin_update_list = await get_plugin_update_list()
  File "/root/nonebot11/.venv/lib/python3.10/site-packages/nonebot_plugin_updater/utils/common.py", line 45, in get_plugin_update_list
    lastest_version = await get_plugin_latest_version(plugin)
  File "/root/nonebot11/.venv/lib/python3.10/site-packages/nonebot_plugin_updater/utils/common.py", line 18, in get_plugin_latest_version
    data: PypiResponse = PypiResponse(**response.json())
  File "/root/nonebot11/.venv/lib/python3.10/site-packages/pydantic/main.py", line 212, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for PypiResponse
info.author_email
  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.9/v/string_type

这是检查更新和更新插件的报错

**Comment by hanasa2023** [comment]
在0.1.3中已修复，可以等待商店检查后再进行测试

**Comment by hanasa2023** [comment]
在0.1.3中已修复，可以等待商店检查通过后再进行测试

**Comment by wzq10314** [comment]
> 在0.1.3中已修复，可以等待商店检查通过后再进行测试

我去浅浅尝试了下更新插件
10-11 00:40:49 [SUCCESS] nonebot | OneBot V11 570502551 | [message.group.normal]: Message 2057912011 from 245176264@[群:163722659] '/更新插件 name nonebot-plugin-updater'
10-11 00:40:49 [INFO] nonebot | Event will be handled by AlconnaMatcher(type='', module=nonebot_plugin_updater.commands, lineno=42)
10-11 00:40:50 [INFO] uvicorn | Shutting down
10-11 00:40:50 [WARNING] nonebot | OneBot V11 | WebSocket for Bot 570502551 closed by peer
10-11 00:40:50 [INFO] websockets | connection closed
10-11 00:40:50 [INFO] uvicorn | Waiting for application shutdown.
10-11 00:40:50 [INFO] nonebot_plugin_htmlrender | Browser Stopped.
10-11 00:40:50 [INFO] uvicorn | Application shutdown complete.
10-11 00:40:50 [INFO] nonebot | AlconnaMatcher(type='', module=nonebot_plugin_updater.commands, lineno=42) running complete
10-11 00:40:50 [INFO] uvicorn | Shutting down
10-11 00:40:50 [INFO] uvicorn | Waiting for application shutdown.
10-11 00:40:50 [INFO] uvicorn | Application shutdown complete.
10-11 00:40:50 [INFO] uvicorn | Finished server process [1130092]


没有报错了emmm但好像会自动关进程也不会重启

**Comment by hanasa2023** [comment]
等今天下午的更新吧，现在有点太晚了（）

**Comment by wzq10314** [comment]
> 等今天下午的更新吧，现在有点太晚了（）
辛苦了！不着急

**Comment by hanasa2023** [comment]
在0.1.5中已修复上述问题，可以耐心等待商店测试通过后再更新该插件（或者手动安装最新版本）。请确保已安装的版本为0.1.5。

**Comment by wzq10314** [comment]
话说测试的里面就我出现问题吗？还是不行，包括基本命令/重启 也无法重启，只会直接关闭
更新报错：55167837 from 245176264@[群:163722659] '/更新插件 nonebot-plugin-updater'
10-11 17:25:36 [INFO] nonebot | Event will be handled by AlconnaMatcher(type='', module=nonebot_plugin_updater.commands, lineno=40)
10-11 17:25:42 [INFO] uvicorn | Shutting down
10-11 17:25:42 [WARNING] nonebot | OneBot V11 | WebSocket for Bot 570502551 closed by peer
10-11 17:25:42 [INFO] websockets | connection closed
10-11 17:25:42 [INFO] uvicorn | Waiting for application shutdown.
10-11 17:25:42 [INFO] nonebot_plugin_htmlrender | Browser Stopped.
10-11 17:25:42 [INFO] uvicorn | Application shutdown complete.
10-11 17:25:42 [ERROR] nonebot_plugin_updater | [Errno 2] No such file or directory: 'nb plugin update nonebot-plugin-updater'
Traceback (most recent call last):
  File "<string>", line 15, in <module>
  File "/root/nonebot11/.venv/lib/python3.10/site-packages/nonebot/__init__.py", line 335, in run
    get_driver().run(*args, **kwargs)
  File "/root/nonebot11/.venv/lib/python3.10/site-packages/nonebot/drivers/fastapi.py", line 186, in run
    uvicorn.run(
  File "/root/nonebot11/.venv/lib/python3.10/site-packages/uvicorn/main.py", line 579, in run
    server.run()
  File "/root/nonebot11/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/root/nonebot11/.venv/lib/python3.10/site-packages/nonebot/message.py", line 476, in check_and_run_matcher
    await _run_matcher(
  File "/root/nonebot11/.venv/lib/python3.10/site-packages/nonebot/message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/root/nonebot11/.venv/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 850, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/root/nonebot11/.venv/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 825, in simple_run
    await handler(
  File "/root/nonebot11/.venv/lib/python3.10/site-packages/nonebot/dependencies/__init__.py", line 94, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/root/nonebot11/.venv/lib/python3.10/site-packages/nonebot_plugin_updater/commands.py", line 116, in _
    await updater.do_update()
> File "/root/nonebot11/.venv/lib/python3.10/site-packages/nonebot_plugin_updater/utils/updater.py", line 99, in do_update
    subprocess.run(
  File "/usr/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'nb plugin update nonebot-plugin-updater'
10-11 17:25:42 [INFO] nonebot | AlconnaMatcher(type='', module=nonebot_plugin_updater.commands, lineno=40) running complete
10-11 17:25:42 [INFO] uvicorn | Shutting down
10-11 17:25:42 [INFO] uvicorn | Waiting for application shutdown.
10-11 17:25:42 [INFO] uvicorn | Application shutdown complete.
10-11 17:25:42 [INFO] uvicorn | Finished server process [1470849]
--------------------------------------------------------------------------------------------------------------------------------------------
/重启:10-11 17:27:51 [SUCCESS] nonebot | OneBot V11 570502551 | [message.group.normal]: Message 815945443 from 245176264@[群:163722659] '/重启nb'
10-11 17:27:51 [INFO] nonebot | Event will be handled by AlconnaMatcher(type='', module=nonebot_plugin_updater.commands, lineno=46)
10-11 17:27:51 [INFO] uvicorn | Shutting down
10-11 17:27:51 [WARNING] nonebot | OneBot V11 | WebSocket for Bot 570502551 closed by peer
10-11 17:27:51 [INFO] websockets | connection closed
10-11 17:27:51 [INFO] uvicorn | Waiting for application shutdown.
10-11 17:27:51 [INFO] nonebot_plugin_htmlrender | Browser Stopped.
10-11 17:27:51 [INFO] uvicorn | Application shutdown complete.
10-11 17:27:51 [INFO] nonebot | AlconnaMatcher(type='', module=nonebot_plugin_updater.commands, lineno=46) running complete
10-11 17:27:51 [INFO] uvicorn | Shutting down
10-11 17:27:51 [INFO] uvicorn | Waiting for application shutdown.
10-11 17:27:51 [INFO] uvicorn | Application shutdown complete.
10-11 17:27:51 [INFO] uvicorn | Finished server process [1471693]

**Comment by hanasa2023** [comment]
> 话说测试的里面就我出现问题吗？还是不行，包括基本命令/重启 也无法重启，只会直接关闭
> 
> 更新报错：55167837 from 245176264@[群:163722659] '/更新插件 nonebot-plugin-updater'
> 
> 10-11 17:25:36 [INFO] nonebot | Event will be handled by AlconnaMatcher(type='', module=nonebot_plugin_updater.commands, lineno=40)
> 
> 10-11 17:25:42 [INFO] uvicorn | Shutting down
> 
> 10-11 17:25:42 [WARNING] nonebot | OneBot V11 | WebSocket for Bot 570502551 closed by peer
> 
> 10-11 17:25:42 [INFO] websockets | connection closed
> 
> 10-11 17:25:42 [INFO] uvicorn | Waiting for application shutdown.
> 
> 10-11 17:25:42 [INFO] nonebot_plugin_htmlrender | Browser Stopped.
> 
> 10-11 17:25:42 [INFO] uvicorn | Application shutdown complete.
> 
> 10-11 17:25:42 [ERROR] nonebot_plugin_updater | [Errno 2] No such file or directory: 'nb plugin update nonebot-plugin-updater'
> 
> Traceback (most recent call last):
> 
>   File "<string>", line 15, in <module>
> 
>   File "/root/nonebot11/.venv/lib/python3.10/site-packages/nonebot/__init__.py", line 335, in run
> 
>     get_driver().run(*args, **kwargs)
> 
>   File "/root/nonebot11/.venv/lib/python3.10/site-packages/nonebot/drivers/fastapi.py", line 186, in run
> 
>     uvicorn.run(
> 
>   File "/root/nonebot11/.venv/lib/python3.10/site-packages/uvicorn/main.py", line 579, in run
> 
>     server.run()
> 
>   File "/root/nonebot11/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 65, in run
> 
>     return asyncio.run(self.serve(sockets=sockets))
> 
>   File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
> 
>     return loop.run_until_complete(main)
> 
>   File "/root/nonebot11/.venv/lib/python3.10/site-packages/nonebot/message.py", line 476, in check_and_run_matcher
> 
>     await _run_matcher(
> 
>   File "/root/nonebot11/.venv/lib/python3.10/site-packages/nonebot/message.py", line 428, in _run_matcher
> 
>     await matcher.run(bot, event, state, stack, dependency_cache)
> 
>   File "/root/nonebot11/.venv/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 850, in run
> 
>     await self.simple_run(bot, event, state, stack, dependency_cache)
> 
>   File "/root/nonebot11/.venv/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 825, in simple_run
> 
>     await handler(
> 
>   File "/root/nonebot11/.venv/lib/python3.10/site-packages/nonebot/dependencies/__init__.py", line 94, in __call__
> 
>     return await cast(Callable[..., Awaitable[R]], self.call)(**values)
> 
>   File "/root/nonebot11/.venv/lib/python3.10/site-packages/nonebot_plugin_updater/commands.py", line 116, in _
> 
>     await updater.do_update()
> 
> > File "/root/nonebot11/.venv/lib/python3.10/site-packages/nonebot_plugin_updater/utils/updater.py", line 99, in do_update
> 
>     subprocess.run(
> 
>   File "/usr/lib/python3.10/subprocess.py", line 503, in run
> 
>     with Popen(*popenargs, **kwargs) as process:
> 
>   File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
> 
>     self._execute_child(args, executable, preexec_fn, close_fds,
> 
>   File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
> 
>     raise child_exception_type(errno_num, err_msg, err_filename)
> 
> FileNotFoundError: [Errno 2] No such file or directory: 'nb plugin update nonebot-plugin-updater'
> 
> 10-11 17:25:42 [INFO] nonebot | AlconnaMatcher(type='', module=nonebot_plugin_updater.commands, lineno=40) running complete
> 
> 10-11 17:25:42 [INFO] uvicorn | Shutting down
> 
> 10-11 17:25:42 [INFO] uvicorn | Waiting for application shutdown.
> 
> 10-11 17:25:42 [INFO] uvicorn | Application shutdown complete.
> 
> 10-11 17:25:42 [INFO] uvicorn | Finished server process [1470849]
> 
> --------------------------------------------------------------------------------------------------------------------------------------------
> 
> /重启:10-11 17:27:51 [SUCCESS] nonebot | OneBot V11 570502551 | [message.group.normal]: Message 815945443 from 245176264@[群:163722659] '/重启nb'
> 
> 10-11 17:27:51 [INFO] nonebot | Event will be handled by AlconnaMatcher(type='', module=nonebot_plugin_updater.commands, lineno=46)
> 
> 10-11 17:27:51 [INFO] uvicorn | Shutting down
> 
> 10-11 17:27:51 [WARNING] nonebot | OneBot V11 | WebSocket for Bot 570502551 closed by peer
> 
> 10-11 17:27:51 [INFO] websockets | connection closed
> 
> 10-11 17:27:51 [INFO] uvicorn | Waiting for application shutdown.
> 
> 10-11 17:27:51 [INFO] nonebot_plugin_htmlrender | Browser Stopped.
> 
> 10-11 17:27:51 [INFO] uvicorn | Application shutdown complete.
> 
> 10-11 17:27:51 [INFO] nonebot | AlconnaMatcher(type='', module=nonebot_plugin_updater.commands, lineno=46) running complete
> 
> 10-11 17:27:51 [INFO] uvicorn | Shutting down
> 
> 10-11 17:27:51 [INFO] uvicorn | Waiting for application shutdown.
> 
> 10-11 17:27:51 [INFO] uvicorn | Application shutdown complete.
> 
> 10-11 17:27:51 [INFO] uvicorn | Finished server process [1471693]

请检查你的插件版本，nb商店那边插件检测还没过。可能需要等待几个小时。

**Comment by hanasa2023** [comment]
> 大佬可以出个不依赖htmlrender的吗 txt2img或纯文本

后续版本可以考虑使用pillow替换htmlrender，不过为什么不想使用htmlrender呢？是playwright装不上么？另外，你应该另外开个issue，而不是在此issue下评论😧

**Comment by wzq10314** [comment]
> > 话说测试的里面就我出现问题吗？还是不行，包括基本命令/重启 也无法重启，只会直接关闭
> > 更新报错：55167837 from 245176264@[群:163722659] '/更新插件 nonebot-plugin-updater'
> > 10-11 17:25:36 [INFO] nonebot | Event will be handled by AlconnaMatcher(type='', module=nonebot_plugin_updater.commands, lineno=40)
> > 10-11 17:25:42 [INFO] uvicorn | Shutting down
> > 10-11 17:25:42 [WARNING] nonebot | OneBot V11 | WebSocket for Bot 570502551 closed by peer
> > 10-11 17:25:42 [INFO] websockets | connection closed
> > 10-11 17:25:42 [INFO] uvicorn | Waiting for application shutdown.
> > 10-11 17:25:42 [INFO] nonebot_plugin_htmlrender | Browser Stopped.
> > 10-11 17:25:42 [INFO] uvicorn | Application shutdown complete.
> > 10-11 17:25:42 [ERROR] nonebot_plugin_updater | [Errno 2] No such file or directory: 'nb plugin update nonebot-plugin-updater'
> > Traceback (most recent call last):
> > File "", line 15, in 
> > File "/root/nonebot11/.venv/lib/python3.10/site-packages/nonebot/**init**.py", line 335, in run
> > ```
> > get_driver().run(*args, **kwargs)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > File "/root/nonebot11/.venv/lib/python3.10/site-packages/nonebot/drivers/fastapi.py", line 186, in run
> > ```
> > uvicorn.run(
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > File "/root/nonebot11/.venv/lib/python3.10/site-packages/uvicorn/main.py", line 579, in run
> > ```
> > server.run()
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > File "/root/nonebot11/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 65, in run
> > ```
> > return asyncio.run(self.serve(sockets=sockets))
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
> > ```
> > return loop.run_until_complete(main)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > File "/root/nonebot11/.venv/lib/python3.10/site-packages/nonebot/message.py", line 476, in check_and_run_matcher
> > ```
> > await _run_matcher(
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > File "/root/nonebot11/.venv/lib/python3.10/site-packages/nonebot/message.py", line 428, in _run_matcher
> > ```
> > await matcher.run(bot, event, state, stack, dependency_cache)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > File "/root/nonebot11/.venv/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 850, in run
> > ```
> > await self.simple_run(bot, event, state, stack, dependency_cache)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > File "/root/nonebot11/.venv/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 825, in simple_run
> > ```
> > await handler(
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > File "/root/nonebot11/.venv/lib/python3.10/site-packages/nonebot/dependencies/**init**.py", line 94, in **call**
> > ```
> > return await cast(Callable[..., Awaitable[R]], self.call)(**values)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > File "/root/nonebot11/.venv/lib/python3.10/site-packages/nonebot_plugin_updater/commands.py", line 116, in _
> > ```
> > await updater.do_update()
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > > File "/root/nonebot11/.venv/lib/python3.10/site-packages/nonebot_plugin_updater/utils/updater.py", line 99, in do_update
> > 
> > 
> > ```
> > subprocess.run(
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > File "/usr/lib/python3.10/subprocess.py", line 503, in run
> > ```
> > with Popen(*popenargs, **kwargs) as process:
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > File "/usr/lib/python3.10/subprocess.py", line 971, in **init**
> > ```
> > self._execute_child(args, executable, preexec_fn, close_fds,
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
> > ```
> > raise child_exception_type(errno_num, err_msg, err_filename)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > FileNotFoundError: [Errno 2] No such file or directory: 'nb plugin update nonebot-plugin-updater'
> > 10-11 17:25:42 [INFO] nonebot | AlconnaMatcher(type='', module=nonebot_plugin_updater.commands, lineno=40) running complete
> > 10-11 17:25:42 [INFO] uvicorn | Shutting down
> > 10-11 17:25:42 [INFO] uvicorn | Waiting for application shutdown.
> > 10-11 17:25:42 [INFO] uvicorn | Application shutdown complete.
> > 10-11 17:25:42 [INFO] uvicorn | Finished server process [1470849]
> > 
> > /重启:10-11 17:27:51 [SUCCESS] nonebot | OneBot V11 570502551 | [message.group.normal]: Message 815945443 from 245176264@[群:163722659] '/重启nb'
> > 10-11 17:27:51 [INFO] nonebot | Event will be handled by AlconnaMatcher(type='', module=nonebot_plugin_updater.commands, lineno=46)
> > 10-11 17:27:51 [INFO] uvicorn | Shutting down
> > 10-11 17:27:51 [WARNING] nonebot | OneBot V11 | WebSocket for Bot 570502551 closed by peer
> > 10-11 17:27:51 [INFO] websockets | connection closed
> > 10-11 17:27:51 [INFO] uvicorn | Waiting for application shutdown.
> > 10-11 17:27:51 [INFO] nonebot_plugin_htmlrender | Browser Stopped.
> > 10-11 17:27:51 [INFO] uvicorn | Application shutdown complete.
> > 10-11 17:27:51 [INFO] nonebot | AlconnaMatcher(type='', module=nonebot_plugin_updater.commands, lineno=46) running complete
> > 10-11 17:27:51 [INFO] uvicorn | Shutting down
> > 10-11 17:27:51 [INFO] uvicorn | Waiting for application shutdown.
> > 10-11 17:27:51 [INFO] uvicorn | Application shutdown complete.
> > 10-11 17:27:51 [INFO] uvicorn | Finished server process [1471693]
> 
> 请检查你的插件版本，nb商店那边插件检测还没过。可能需要等待几个小时。

还是这个情况 重启还是会直接关闭进程不会自动启动 v0.1.5

**Comment by hanasa2023** [comment]
可以尝试0.1.7是否修复，请注意此版本的指令鉴权。如未修复😵，能否提供现存的有问题的指令及其日志

**Comment by wzq10314** [comment]
> 可以尝试0.1.7是否修复，请注意此版本的指令鉴权。如未修复😵，能否提供现存的有问题的指令及其日志

感谢已经没问题了
