### ISSUE TITLE
关于不再依赖htmlrender的提议

### ISSUE THREAD

**Issue by ArcPav** [hanasa2023/nonebot-plugin-updater#3]
大佬求求您了 可以不依赖htmlrender吗 txt2img或纯文本
原因是playwright装不了 因为运行在termux上

**Comment by hanasa2023** [comment]
那我在后续版本中使用pillow替代html render吧

**Comment by hanasa2023** [comment]
可以试试>=0.1.8的版本。从0.1.8开始，启动不自动加载plugin-htmlrender，填写info_send_mode为text后，则不加载htmlrender。这应该能够解决无法安装playwright的问题。
