### ISSUE TITLE
Good

### ISSUE THREAD

**Issue by Reversedeer** [hanasa2023/nonebot-plugin-updater#8]
一个很好的插件，我很早就已经想实现这个功能，但是苦于上学没时间qwq,去年就已经产生这个想法，项目处于半成品所以一直没发版，近期想重拾这个未完成的项目，遂发现作者实现了部分功能。
后面在完善我的插件时想参考下作者的写法，也可以向我发邮件获取联系方式:）期待!

**Comment by hanasa2023** [comment]
很高兴能够看到这样的issue，希望我的实现方式能够对你有帮助。如需联系可以通过Mail:hanasakayui2022@gmail.com联系。如果没有什么其他问题，我会在明天关闭这个issue XD
